### ISSUE TITLE
Source icons still not included

### ISSUE THREAD

**Issue by zoccoler** [BiAPoL/biaplotter#19]
I tried installing `0.0.3` which should now contain the icons, but they did no show up in the plotter yet.

This should have been fixed via #17 , but it still does not work for me.

**Comment by haesleinhuepf** [comment]
Hi Marcelo @zoccoler 

I just saw this issue and know what pain it can be to make these things work. The folder specified in #17 : 
https://github.com/BiAPoL/biaplotter/blob/9d1315256f14d8d4e120d79fe29f2aaebf833922/MANIFEST.in#L7

does not exist. Try this folder instead:
[src/biaplotter/icons](https://github.com/BiAPoL/biaplotter/tree/main/src/biaplotter/icons)

One can test this by executing [this line](https://github.com/BiAPoL/biaplotter/blob/9d1315256f14d8d4e120d79fe29f2aaebf833922/.github/workflows/test_and_deploy.yml#L95C11-L95C28) on a local terminal. The output should then contain lines such as:
```
adding 'biaplotter/icons/button1.png'
```

Best,
Robert

**Comment by zoccoler** [comment]
Hi @haesleinhuepf ,

Thank you, this was fixed yesterday by @stefanhahmann in #20 :)
I released a new version after that (`0.0.4`), it should be working now, if not please let me know, otherwise, please feel free to close this issue.

Best,
Marcelo

**Comment by zoccoler** [comment]
I am closing this, please re-open in case the problem persists.
